version: '3'

services:

  mysql-development:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tmg
    ports:
      - "3308:3306"