import Document, { Html, Head, Main, NextScript } from "next/document";

export default class MyDocument extends Document {
  render() {
    return (
      <Html>
      <Head>
        {/* tailwindcss */}
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />

        <link rel="shortcut icon" href="/images/logo.png" type="image/png" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
      </Html>
    );
  }
}
