import { NextApiRequest, NextApiResponse } from "next";

export default (req: NextApiRequest, res: NextApiResponse) => {
  try {
    const users = [
      {
        id: 1,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 2,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
      {
        id: 3,
        name: 'Fulano da Silva Sauro',
        nickname: 'FULANO SILVA',
        telefone: '(11) 1234-123',
        email: 'fulano.silva@agroforce.com.br',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eKClhijhzBYGKsSP-kDvZsXFhu8cdiJXzA&usqp=CAU',
        status: false,
      },{
        id: 4,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 5,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
      {
        id: 6,
        name: 'Fulano da Silva Sauro',
        nickname: 'FULANO SILVA',
        telefone: '(11) 1234-123',
        email: 'fulano.silva@agroforce.com.br',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eKClhijhzBYGKsSP-kDvZsXFhu8cdiJXzA&usqp=CAU',
        status: false,
      },{
        id: 7,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 8,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
      {
        id: 9,
        name: 'Fulano da Silva Sauro',
        nickname: 'FULANO SILVA',
        telefone: '(11) 1234-123',
        email: 'fulano.silva@agroforce.com.br',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eKClhijhzBYGKsSP-kDvZsXFhu8cdiJXzA&usqp=CAU',
        status: false,
      },{
        id: 10,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 11,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
      {
        id: 12,
        name: 'Fulano da Silva Sauro',
        nickname: 'FULANO SILVA',
        telefone: '(11) 1234-123',
        email: 'fulano.silva@agroforce.com.br',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eKClhijhzBYGKsSP-kDvZsXFhu8cdiJXzA&usqp=CAU',
        status: false,
      },{
        id: 13,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 14,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
      {
        id: 15,
        name: 'Fulano da Silva Sauro',
        nickname: 'FULANO SILVA',
        telefone: '(11) 1234-123',
        email: 'fulano.silva@agroforce.com.br',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eKClhijhzBYGKsSP-kDvZsXFhu8cdiJXzA&usqp=CAU',
        status: false,
      },{
        id: 16,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 17,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
      {
        id: 18,
        name: 'Fulano da Silva Sauro',
        nickname: 'FULANO SILVA',
        telefone: '(11) 1234-123',
        email: 'fulano.silva@agroforce.com.br',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_eKClhijhzBYGKsSP-kDvZsXFhu8cdiJXzA&usqp=CAU',
        status: false,
      },{
        id: 19,
        name: 'Paulo Cesar',
        nickname: 'PAULO CESAR',
        telefone: '(11) 1234-123',
        email: 'paulo.jomo@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/55369778?v=4',
        status: true,
      },
      {
        id: 20,
        name: 'Jonatas Rosa Moura',
        nickname: 'JONATAS R MOURA',
        telefone: '(11) 1234-123',
        email: 'jonatas.moura@agroforce.com.br',
        image: 'https://avatars.githubusercontent.com/u/66448546?s=400&u=f9dba4fdf4ff112c31e59860f23578a994deb838&v=4',
        status: true,
      },
    ]
  
    return res.json(users);
  } catch (err) {
    res.status(400).json(err);
  }
}
