# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [12.x]

    steps:          

    # Setup gcloud CLI
    #https://cloud.google.com/iam/docs/creating-managing-service-account-keys
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: machine-learning-195414
        export_default_credentials: true
        
    - run: |-
        gcloud components install --quiet beta
    - run: |-
        gcloud beta compute ssh --zone "southamerica-east1-b" "dev-server" --project "machine-learning-195414" --command 'sudo /root/tmg.sh'